version: '3.8' # или другая версия, которую вы используете
services:
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=NewC0mpl3xP@ssw0rd!
      - MSSQL_PID=Developer