configuration:
  host: localhost
  port: 8080
  version: v1
  api: api
  mssqlDsn: localhost;user id=sa;password=NewC0mpl3xP@ssw0rd!;port=1433;database=master;encrypt=disable;TrustServerCertificate=true;